<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Department;
use App\Models\Item;
use App\Models\Unit;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $pcs  = Unit::where('abbreviation', 'pcs')->first()->id;
        $kg   = Unit::where('abbreviation', 'kg')->first()->id;
        $L    = Unit::where('abbreviation', 'L')->first()->id;
        $set  = Unit::where('abbreviation', 'set')->first()->id;
        $sack = Unit::where('abbreviation', 'sack')->first()->id;
        $btl  = Unit::where('abbreviation', 'btl')->first()->id;
        $pack = Unit::where('abbreviation', 'pack')->first()->id;
        $box  = Unit::where('abbreviation', 'box')->first()->id;
        $can  = Unit::where('abbreviation', 'can')->first()->id;
        $roll = Unit::where('abbreviation', 'roll')->first()->id;
        $pair = Unit::where('abbreviation', 'pair')->first()->id;

        $dept = fn(string $code) => Department::where('code', $code)->first()?->id;

        $cat = fn(string $catName, string $deptCode) => Category::where('name', $catName)
            ->where('department_id', $dept($deptCode))
            ->first()?->id;

        $god = 'GOD';

        $items = [

            // ── FIXED ASSETS ──────────────────────────────────────────────

            ['name' => 'Toshiba Inverter Refrigerator', 'description' => 'Commercial upright inverter refrigerator for food storage',  'category_id' => $cat('SUPPLIES', $god), 'unit_id' => $pcs, 'item_type' => 'fixed_asset', 'brand' => 'Toshiba', 'model' => 'GR-A28 Inverter',       'specifications' => ['capacity' => '268L', 'cooling' => 'Inverter Compressor', 'configuration' => '2-door Top-freezer'], 'min_stock_level' => 0, 'department_id' => $dept($god)],
            ['name' => 'Modena Commercial Gas Range',   'description' => '6-burner commercial gas range with oven and auto-ignition',  'category_id' => $cat('SUPPLIES', $god), 'unit_id' => $pcs, 'item_type' => 'fixed_asset', 'brand' => 'Modena', 'model' => 'CS 6640 EX',            'specifications' => ['burners' => '6 cast-iron', 'ignition' => 'Auto-ignition', 'oven' => 'Yes, electric'],              'min_stock_level' => 0, 'department_id' => $dept($god)],
            ['name' => 'Meyer Accolade Cookware Set',   'description' => '14-piece tri-ply stainless steel commercial cookware set',   'category_id' => $cat('SUPPLIES', $god), 'unit_id' => $set, 'item_type' => 'fixed_asset', 'brand' => 'Meyer',   'model' => 'Accolade Series 14-Piece', 'specifications' => ['pieces' => 14, 'material' => 'Tri-ply stainless steel', 'induction_ready' => true],            'min_stock_level' => 0, 'department_id' => $dept($god)],

            // ── BEEF ──────────────────────────────────────────────────────

            ['name' => 'Beef - Sliced',  'description' => 'Sliced beef for stir-fry and dishes', 'category_id' => $cat('BEEF', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Beef Brisket',   'description' => 'Beef brisket cut',                    'category_id' => $cat('BEEF', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Bulalo / Kansi', 'description' => 'Beef shank and marrow for bulalo',    'category_id' => $cat('BEEF', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Ground Beef',    'description' => 'Ground beef',                         'category_id' => $cat('BEEF', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Oxtripe',        'description' => 'Beef tripe',                          'category_id' => $cat('BEEF', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Top Round Beef', 'description' => 'Top round beef cut',                  'category_id' => $cat('BEEF', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],

            // ── PORK ──────────────────────────────────────────────────────

            ['name' => 'Bopis',                       'description' => 'Pork lungs and heart for bopis', 'category_id' => $cat('PORK', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Ground Pork',                 'description' => 'Ground pork',                   'category_id' => $cat('PORK', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Liempo',                      'description' => 'Pork belly (liempo)',            'category_id' => $cat('PORK', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Liempo Slice',                'description' => 'Sliced pork belly',             'category_id' => $cat('PORK', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Pork BBQ',                    'description' => 'Pork cuts for BBQ',             'category_id' => $cat('PORK', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Pork Chop',                   'description' => 'Pork chop cut',                 'category_id' => $cat('PORK', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Pork Liver',                  'description' => 'Pork liver',                    'category_id' => $cat('PORK', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Pork Gizzard (Balunbalunan)', 'description' => 'Pork gizzard',                  'category_id' => $cat('PORK', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Pork Maskara',                'description' => 'Pork face (maskara)',            'category_id' => $cat('PORK', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Pork Pata',                   'description' => 'Pork knuckle (pata)',            'category_id' => $cat('PORK', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Pork Pigue',                  'description' => 'Pork ham / hind leg',           'category_id' => $cat('PORK', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Spareribs',                   'description' => 'Pork spareribs',                'category_id' => $cat('PORK', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],

            // ── CHICKEN ───────────────────────────────────────────────────

            ['name' => 'Chicken Breast',  'description' => 'Boneless chicken breast',   'category_id' => $cat('CHICKEN', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Chicken Gizzard', 'description' => 'Chicken gizzard',            'category_id' => $cat('CHICKEN', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Chicken Liver',   'description' => 'Chicken liver',              'category_id' => $cat('CHICKEN', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Chicken Thigh',   'description' => 'Chicken thigh cut',          'category_id' => $cat('CHICKEN', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Chicken Whole',   'description' => 'Whole dressed chicken',      'category_id' => $cat('CHICKEN', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Chicken Wings',   'description' => 'Chicken wings',              'category_id' => $cat('CHICKEN', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],

            // ── SEAFOOD ───────────────────────────────────────────────────

            ['name' => 'Alumahan',          'description' => 'Indian mackerel',                  'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Bagoong Alamang',   'description' => 'Fermented shrimp paste',           'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Bisugo',            'description' => 'Threadfin bream',                  'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Daing na Bangus',   'description' => 'Dried marinated milkfish',         'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Daing na Galunggong', 'description' => 'Dried marinated round scad',    'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Dalagang Bukid',    'description' => 'Fusilier fish',                    'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Dry Dilis',         'description' => 'Dried anchovies',                  'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Fish Fillet',       'description' => 'Fish fillet (assorted)',            'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Galunggong',        'description' => 'Round scad',                       'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Hasa-hasa',         'description' => 'Short mackerel',                   'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Matangbaka',        'description' => 'Bigeye scad',                      'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Maya-maya',         'description' => 'Red snapper',                      'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Bangus Boneless',   'description' => 'Boneless milkfish (bangus)',        'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Mussels',           'description' => 'Fresh mussels (tahong)',            'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Okoy',              'description' => 'Shrimp (for okoy)',                 'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Pink Salmon Head',  'description' => 'Pink salmon head',                 'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Salmon Local',      'description' => 'Local salmon fish',                 'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Shrimp / Swahe',    'description' => 'Shrimp (swahe)',                   'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Squid',             'description' => 'Fresh squid (pusit)',               'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Tambakol',          'description' => 'Yellowfin tuna',                   'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Tilapia Whole',     'description' => 'Whole tilapia fish',                'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Tulingan',          'description' => 'Bullet tuna',                      'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Tuyo Salinas',      'description' => 'Dried salted sardines (tuyo)',     'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Tanigue',           'description' => 'Spanish mackerel',                 'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Tawilis',           'description' => 'Freshwater herring',               'category_id' => $cat('SEAFOOD', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],

            // ── PROCESSED MEATS ───────────────────────────────────────────

            ['name' => 'Bacon',                    'description' => 'Bacon strips',                         'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Beef Burger Patties',      'description' => 'Frozen beef burger patties',           'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Beef Steak',               'description' => 'Processed beef steak',                 'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Cheesedog',                'description' => 'Cheese-filled hotdog',                 'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Chicken Franks',           'description' => 'Chicken frankfurter sausages',         'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Chicken Nuggets',          'description' => 'Breaded chicken nuggets',              'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Chicken Tocino',           'description' => 'Cured sweet chicken (tocino)',          'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Corned Beef',              'description' => 'Canned corned beef',                   'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $can, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Daing na Bangus (Packed)', 'description' => 'Packaged / processed daing na bangus', 'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Embotido',                 'description' => 'Filipino meat loaf roll',              'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Garlic Longganisa',        'description' => 'Garlic-seasoned pork sausage',         'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Garlic Sausage',           'description' => 'Garlic-flavored sausage',              'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Ham',                      'description' => 'Cured ham',                            'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Hotdog',                   'description' => 'Hotdog sausages',                      'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Hungarian Sausage',        'description' => 'Hungarian-style pork sausage',         'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Longganisa',               'description' => 'Filipino pork sausage',                'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Meatballs',                'description' => 'Frozen pork or beef meatballs',        'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Meatloaf',                 'description' => 'Canned or frozen meatloaf',            'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Pork Tapa',                'description' => 'Cured pork tapa',                      'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Pork Tocino',              'description' => 'Cured sweet pork (tocino)',             'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Siomai',                   'description' => 'Pork or shrimp siomai dumplings',      'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Sweet Ham',                'description' => 'Sweet-cured ham',                      'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Beef Tapa',                'description' => 'Cured beef tapa',                      'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Tinapa',                   'description' => 'Smoked fish (tinapa)',                  'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Vienna Sausage',           'description' => 'Canned vienna sausage',                'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $can, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Sisig Sausage',            'description' => 'Sisig-flavored sausage',               'category_id' => $cat('PROCESSED MEATS', $god), 'unit_id' => $kg,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],

            // ── VEGETABLES ────────────────────────────────────────────────

            ['name' => 'Alugbati',                'description' => 'Alugbati (Malabar spinach)',     'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Ampalaya',                'description' => 'Bitter gourd (ampalaya)',        'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Baguio Beans',            'description' => 'Green beans (Baguio beans)',     'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Baguio Lettuce',          'description' => 'Lettuce (Baguio)',               'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Banana Blossom',          'description' => 'Banana blossom (puso ng saging)','category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Bell Pepper (Red & Green)', 'description' => 'Red and green bell peppers',  'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Brocolli',                'description' => 'Fresh broccoli',                'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Cabbage',                 'description' => 'Fresh cabbage',                 'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Calamansi',               'description' => 'Calamansi (Philippine lime)',   'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Carrots',                 'description' => 'Fresh carrots',                 'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Cauliflower',             'description' => 'Fresh cauliflower',             'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Chili Finger (Green)',    'description' => 'Green finger chili',            'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Chili Labuyo (Red)',      'description' => 'Red labuyo chili',              'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Cucumber',                'description' => 'Fresh cucumber',                'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Dahon ng Sili',           'description' => 'Chili leaves',                 'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Eggplant',                'description' => 'Fresh eggplant (talong)',       'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Gabi Root',               'description' => 'Taro root (gabi)',              'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Fresh Garlic',            'description' => 'Fresh garlic bulbs',            'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Fresh Gata',              'description' => 'Fresh coconut milk (gata)',     'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $L,    'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Ginger',                  'description' => 'Fresh ginger root (luya)',      'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Green Peas',              'description' => 'Fresh or frozen green peas',    'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Kamote',                  'description' => 'Sweet potato (kamote)',          'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Kangkong',                'description' => 'Water spinach (kangkong)',       'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Labanos',                 'description' => 'White radish (labanos)',         'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Labong',                  'description' => 'Bamboo shoots (labong)',         'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Laing',                   'description' => 'Dried taro leaves (laing)',     'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Langka Gayat',            'description' => 'Sliced young jackfruit',        'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Lettuce',                 'description' => 'Fresh lettuce',                 'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Lumpia Wrapper',          'description' => 'Spring roll wrappers',          'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $pack, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Malunggay',               'description' => 'Moringa leaves (malunggay)',    'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Mixed Vegies',            'description' => 'Mixed vegetables (assorted)',   'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Monggo',                  'description' => 'Mung beans (monggo)',            'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Okra',                    'description' => 'Fresh okra',                    'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Onion Leaves',            'description' => 'Spring onion / green onion',   'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Onion White',             'description' => 'White onion',                  'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Onion Red',               'description' => 'Red onion',                    'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Onion Leaks',             'description' => 'Leeks (onion leeks)',           'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Papaya - Green',          'description' => 'Green / unripe papaya',        'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Patola',                  'description' => 'Sponge gourd (patola)',         'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Pechay Chinese',          'description' => 'Chinese pechay (bok choy)',     'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Pechay Tagalog',          'description' => 'Tagalog pechay (mustard green)','category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Potato',                  'description' => 'Fresh potato',                 'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Kalabasa',                'description' => 'Squash (kalabasa)',             'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Puso ng Saging Gayat',    'description' => 'Sliced banana blossom',        'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Saluyot',                 'description' => 'Jute leaves (saluyot)',         'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Saba',                    'description' => 'Saba banana (cooking banana)',  'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Sayote',                  'description' => 'Chayote (sayote)',              'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Sigarilyas',              'description' => 'Winged beans (sigarilyas)',     'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Singkamas',               'description' => 'Turnip (singkamas)',            'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Sitaw',                   'description' => 'String beans (sitaw)',          'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Sitsaro',                 'description' => 'Snow peas (sitsaro)',           'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Star Anise',              'description' => 'Star anise spice',              'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Lemon Grass',             'description' => 'Lemon grass (tanglad)',         'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Togue',                   'description' => 'Bean sprouts (togue)',          'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Tofu',                    'description' => 'Fresh tofu (tokwa/taho)',       'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Tomato',                  'description' => 'Fresh tomato',                 'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Upo',                     'description' => 'Bottle gourd (upo)',            'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Yellow Corn',             'description' => 'Fresh yellow corn (mais)',      'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Red Beans',               'description' => 'Dried red beans',              'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Young Corn',              'description' => 'Baby corn (young corn)',        'category_id' => $cat('VEGETABLES', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],

            // ── FRESH FRUITS ──────────────────────────────────────────────

            ['name' => 'Apple',                 'description' => 'Fresh apple',                    'category_id' => $cat('FRESH FRUITS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Avocado',               'description' => 'Fresh avocado',                  'category_id' => $cat('FRESH FRUITS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Banana - Lakatan Hilaw', 'description' => 'Unripe lakatan banana',         'category_id' => $cat('FRESH FRUITS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Banana - Lakatan Hinog', 'description' => 'Ripe lakatan banana',           'category_id' => $cat('FRESH FRUITS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Honeydew',              'description' => 'Honeydew melon',                 'category_id' => $cat('FRESH FRUITS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Mango',                 'description' => 'Fresh mango',                    'category_id' => $cat('FRESH FRUITS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Melon',                 'description' => 'Fresh melon',                    'category_id' => $cat('FRESH FRUITS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Orange',                'description' => 'Fresh orange',                   'category_id' => $cat('FRESH FRUITS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Pakwan',                'description' => 'Watermelon (pakwan)',             'category_id' => $cat('FRESH FRUITS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Pineapple',             'description' => 'Fresh pineapple',                'category_id' => $cat('FRESH FRUITS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Ponkan',                'description' => 'Ponkan citrus fruit',            'category_id' => $cat('FRESH FRUITS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],

            // ── RICE ──────────────────────────────────────────────────────

            ['name' => 'Long Grain Rice', 'description' => 'Long grain white rice, 50kg sack', 'category_id' => $cat('RICE', $god), 'unit_id' => $sack, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Japanese Rice',   'description' => 'Short grain Japanese rice',         'category_id' => $cat('RICE', $god), 'unit_id' => $sack, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Malagkit',        'description' => 'Glutinous / sticky rice (malagkit)','category_id' => $cat('RICE', $god), 'unit_id' => $sack, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],

            // ── EGGS ──────────────────────────────────────────────────────

            ['name' => 'White Eggs',   'description' => 'White chicken eggs',  'category_id' => $cat('EGGS', $god), 'unit_id' => $pcs, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 30, 'department_id' => $dept($god)],
            ['name' => 'Salted Eggs',  'description' => 'Salted duck/chicken eggs', 'category_id' => $cat('EGGS', $god), 'unit_id' => $pcs, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],

            // ── CONDIMENTS ────────────────────────────────────────────────

            ['name' => 'Catsup',                    'description' => 'Tomato ketchup',                    'category_id' => $cat('CONDIMENTS', $god), 'unit_id' => $btl, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Hot Sauce',                 'description' => 'Hot sauce',                         'category_id' => $cat('CONDIMENTS', $god), 'unit_id' => $btl, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Kikkoman Soy Sauce',        'description' => 'Kikkoman Japanese soy sauce',       'category_id' => $cat('CONDIMENTS', $god), 'unit_id' => $btl, 'item_type' => 'consumable', 'brand' => 'Kikkoman', 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Knorr Seasoning',           'description' => 'Knorr liquid seasoning',            'category_id' => $cat('CONDIMENTS', $god), 'unit_id' => $btl, 'item_type' => 'consumable', 'brand' => 'Knorr', 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Mang Tomas Lechon Sauce',   'description' => 'Mang Tomas all-purpose sauce',      'category_id' => $cat('CONDIMENTS', $god), 'unit_id' => $btl, 'item_type' => 'consumable', 'brand' => 'Mang Tomas', 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Oyster Sauce',              'description' => 'Oyster sauce',                      'category_id' => $cat('CONDIMENTS', $god), 'unit_id' => $btl, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Fish Sauce',                'description' => 'Fish sauce (patis)',                 'category_id' => $cat('CONDIMENTS', $god), 'unit_id' => $btl, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Soy Sauce',                 'description' => 'Soy sauce (toyo)',                   'category_id' => $cat('CONDIMENTS', $god), 'unit_id' => $btl, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Tabasco',                   'description' => 'Tabasco hot pepper sauce',           'category_id' => $cat('CONDIMENTS', $god), 'unit_id' => $btl, 'item_type' => 'consumable', 'brand' => 'Tabasco', 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Vinegar',                   'description' => 'White cane vinegar (suka)',          'category_id' => $cat('CONDIMENTS', $god), 'unit_id' => $btl, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Honey',                     'description' => 'Natural honey',                     'category_id' => $cat('CONDIMENTS', $god), 'unit_id' => $btl, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],

            // ── SEASONING ─────────────────────────────────────────────────

            ['name' => 'Rock Salt',       'description' => 'Rock salt',                          'category_id' => $cat('SEASONING', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Pepper',          'description' => 'Ground black pepper',                'category_id' => $cat('SEASONING', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Aromat',          'description' => 'Aromat all-purpose seasoning',       'category_id' => $cat('SEASONING', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => 'Aromat', 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Pork Broth',      'description' => 'Pork broth cubes / powder',          'category_id' => $cat('SEASONING', $god), 'unit_id' => $pack, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Chicken Broth',   'description' => 'Chicken broth cubes / powder',       'category_id' => $cat('SEASONING', $god), 'unit_id' => $pack, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Beef Broth',      'description' => 'Beef broth cubes / powder',          'category_id' => $cat('SEASONING', $god), 'unit_id' => $pack, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Chicken Powder',  'description' => 'Chicken seasoning powder',           'category_id' => $cat('SEASONING', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Shrimp Powder',   'description' => 'Shrimp seasoning powder',            'category_id' => $cat('SEASONING', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Sinigang Mix',    'description' => 'Sinigang soup base mix',             'category_id' => $cat('SEASONING', $god), 'unit_id' => $pack, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],

            // ── NOODLES & PASTA ───────────────────────────────────────────

            ['name' => 'Bihon',           'description' => 'Rice vermicelli (bihon)',            'category_id' => $cat('NOODLES & PASTA', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Canton',          'description' => 'Egg noodles (canton)',               'category_id' => $cat('NOODLES & PASTA', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Macaroni Pasta',  'description' => 'Elbow macaroni pasta',              'category_id' => $cat('NOODLES & PASTA', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Miki (Fresh)',    'description' => 'Fresh miki noodles',                'category_id' => $cat('NOODLES & PASTA', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Misua',           'description' => 'Thin wheat vermicelli (misua)',     'category_id' => $cat('NOODLES & PASTA', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Palabok Noodles', 'description' => 'Rice noodles for palabok',         'category_id' => $cat('NOODLES & PASTA', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Sotanghon',       'description' => 'Glass noodles (sotanghon)',         'category_id' => $cat('NOODLES & PASTA', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Spaghetti Pasta', 'description' => 'Spaghetti pasta',                  'category_id' => $cat('NOODLES & PASTA', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],

            // ── OIL ───────────────────────────────────────────────────────

            ['name' => 'Cooking Oil', 'description' => 'Refined cooking oil (palm / canola)', 'category_id' => $cat('OIL', $god), 'unit_id' => $L, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Sesame Oil',  'description' => 'Sesame oil for cooking and flavoring', 'category_id' => $cat('OIL', $god), 'unit_id' => $L, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],

            // ── SUGAR / OTHERS ────────────────────────────────────────────

            ['name' => 'Cornstarch',       'description' => 'Cornstarch powder',            'category_id' => $cat('SUGAR / OTHERS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Sugar, Brown',     'description' => 'Brown sugar',                  'category_id' => $cat('SUGAR / OTHERS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Sugar, White',     'description' => 'White refined sugar',          'category_id' => $cat('SUGAR / OTHERS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'All Purpose Flour', 'description' => 'All-purpose wheat flour',    'category_id' => $cat('SUGAR / OTHERS', $god), 'unit_id' => $kg, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],

            // ── CANNED GOODS ──────────────────────────────────────────────

            ['name' => 'Button Mushroom',            'description' => 'Canned button mushroom',           'category_id' => $cat('CANNED GOODS', $god), 'unit_id' => $can, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Cream of Corn',              'description' => 'Canned cream-style corn',          'category_id' => $cat('CANNED GOODS', $god), 'unit_id' => $can, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Garbanzos',                  'description' => 'Canned chickpeas (garbanzos)',     'category_id' => $cat('CANNED GOODS', $god), 'unit_id' => $can, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Coconut Milk in Can',        'description' => 'Canned coconut milk (gata)',       'category_id' => $cat('CANNED GOODS', $god), 'unit_id' => $can, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Luncheon Meat',              'description' => 'Canned luncheon meat',             'category_id' => $cat('CANNED GOODS', $god), 'unit_id' => $can, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Pork & Beans',               'description' => 'Canned pork and beans',           'category_id' => $cat('CANNED GOODS', $god), 'unit_id' => $can, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Sardines in Tomato Sauce',   'description' => 'Canned sardines in tomato sauce', 'category_id' => $cat('CANNED GOODS', $god), 'unit_id' => $can, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 12, 'department_id' => $dept($god)],
            ['name' => 'Whole Kernel Corn',          'description' => 'Canned whole kernel corn',        'category_id' => $cat('CANNED GOODS', $god), 'unit_id' => $can, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],

            // ── SUPPLIES ──────────────────────────────────────────────────

            ['name' => 'Aluminum Foil', 'description' => 'Heavy-duty aluminum foil roll',      'category_id' => $cat('SUPPLIES', $god), 'unit_id' => $roll, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Cling Wrap',    'description' => 'Plastic cling wrap roll',             'category_id' => $cat('SUPPLIES', $god), 'unit_id' => $roll, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Handgloves',    'description' => 'Disposable food-handling gloves',    'category_id' => $cat('SUPPLIES', $god), 'unit_id' => $box,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],

            // ── OTHERS ────────────────────────────────────────────────────

            ['name' => 'Cream of Pumpkin',       'description' => 'Canned cream of pumpkin soup',       'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Cream of Mushroom',      'description' => 'Canned cream of mushroom soup',      'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Curry Powder',           'description' => 'Curry powder spice mix',             'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Demiglace Sauce',        'description' => 'Demi-glace sauce (powder or paste)', 'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Bread Crumbs',           'description' => 'Bread crumbs for coating',          'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Atsuete',                'description' => 'Annatto seeds / powder (atsuete)',  'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Mushroom Shiitake',      'description' => 'Dried shiitake mushrooms',          'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Peanut Butter',          'description' => 'Peanut butter (creamy or crunchy)', 'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Pineapple Tidbits',      'description' => 'Canned pineapple tidbits',          'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Spanish Paprika',        'description' => 'Spanish paprika powder',            'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Tomato Paste',           'description' => 'Canned tomato paste',               'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Tomato Sauce',           'description' => 'Canned tomato sauce',               'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Pineapple Chunks',       'description' => 'Canned pineapple chunks',           'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Pickle (Whole)',         'description' => 'Whole pickles in brine',            'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Pickle (Relish)',        'description' => 'Pickle relish',                     'category_id' => $cat('OTHERS', $god), 'unit_id' => $btl,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Salted Black Beans',     'description' => 'Canned salted black beans (tausi)', 'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Onion Powder',           'description' => 'Dehydrated onion powder',          'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Liver Spread',           'description' => 'Canned liver spread',              'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'BBQ Marinade',           'description' => 'BBQ marinade sauce',               'category_id' => $cat('OTHERS', $god), 'unit_id' => $btl,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Basil Leaves',           'description' => 'Dried or fresh basil leaves',     'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Mayonnaise',             'description' => 'Mayonnaise (spread)',              'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Crab and Corn',          'description' => 'Canned crab and corn soup',        'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Cheese Sauce Mix',       'description' => 'Powdered cheese sauce mix',        'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Garlic Powder',          'description' => 'Dehydrated garlic powder',        'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Fried Garlic Granules',  'description' => 'Crispy fried garlic granules',   'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Whole Red Parmiento',    'description' => 'Canned whole red pimiento',       'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Charcoal',               'description' => 'Cooking charcoal (uling)',        'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Century Tuna Chunks',    'description' => 'Canned tuna chunks in oil/brine', 'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => 'Century', 'model' => null, 'specifications' => null, 'min_stock_level' => 10, 'department_id' => $dept($god)],
            ['name' => 'Fried Garlic',           'description' => 'Pre-fried garlic topping',        'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Hoisin Sauce',           'description' => 'Chinese hoisin sauce',            'category_id' => $cat('OTHERS', $god), 'unit_id' => $btl,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Sweet Chili Sauce',      'description' => 'Sweet chili dipping sauce',       'category_id' => $cat('OTHERS', $god), 'unit_id' => $btl,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Lard',                   'description' => 'Pork lard (mantika)',             'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3,  'department_id' => $dept($god)],
            ['name' => 'Margarine',              'description' => 'Margarine (butter substitute)',   'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2,  'department_id' => $dept($god)],
            ['name' => 'Rosemary',               'description' => 'Dried rosemary herb',            'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Cayenne Powder',         'description' => 'Cayenne chili powder',           'category_id' => $cat('OTHERS', $god), 'unit_id' => $kg,   'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1,  'department_id' => $dept($god)],
            ['name' => 'Bamboo Shoot',           'description' => 'Canned bamboo shoots (labong)',  'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Straw Mushroom',         'description' => 'Canned straw mushrooms',         'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],
            ['name' => 'Whole Mushroom',         'description' => 'Canned whole mushrooms',         'category_id' => $cat('OTHERS', $god), 'unit_id' => $can,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5,  'department_id' => $dept($god)],

            // ── CLEANING MATERIALS ────────────────────────────────────────

            ['name' => 'All Purpose Cleaner',          'description' => 'All-purpose cleaning solution',         'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $btl,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Chlorine Bleach & Sanitizer',  'description' => 'Chlorine bleach and sanitizer solution','category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $btl,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Compact Tissue (16packs/box)', 'description' => 'Compact tissue box (16 packs)',         'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $box,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Dishwashing Liquid',           'description' => 'Dishwashing liquid detergent',          'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $btl,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Fire Gel',                     'description' => 'Gel fire starter',                      'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Floor Squeegee',               'description' => 'Floor squeegee (rubber blade)',         'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Floor Squeegee Handle',        'description' => 'Replacement handle for floor squeegee', 'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Garbage Bag (Black) Med.',     'description' => 'Black medium garbage bags (pack)',      'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pack, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Garbage Bag (Black) XXL',      'description' => 'Black extra-large garbage bags (pack)', 'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pack, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Hand Soap',                    'description' => 'Liquid hand soap',                      'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $btl,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Mop Bucket Squeezer',          'description' => 'Mop bucket with squeezer wringer',      'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 1, 'department_id' => $dept($god)],
            ['name' => 'Mop Head',                     'description' => 'Replacement mop head',                  'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Mop Handle',                   'description' => 'Mop handle stick',                      'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Pop-up Tissue (60pcs/box)',    'description' => 'Pop-up facial tissue box (60 pcs)',     'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $box,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Pot Holder',                   'description' => 'Heat-resistant pot holder / oven mitt', 'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Push Brush',                   'description' => 'Push/deck scrub brush',                 'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Round Rugs White',             'description' => 'White round floor rugs',                'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Rubber Gloves',                'description' => 'Heavy-duty rubber cleaning gloves',     'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pair, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Scotch Brite 3M',              'description' => '3M Scotch-Brite scrubbing pad',         'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => '3M', 'model' => 'Scotch-Brite', 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Scour Pad w/Foam',             'description' => 'Scouring pad with foam sponge',         'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 5, 'department_id' => $dept($god)],
            ['name' => 'Soft Broom',                   'description' => 'Soft-bristle floor broom (walis tambo)', 'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Spray Bottle',                 'description' => 'Empty spray bottle for cleaning solutions', 'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 3, 'department_id' => $dept($god)],
            ['name' => 'Squeegee w/Foam',              'description' => 'Squeegee with foam sponge attachment',  'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],
            ['name' => 'Stick Broom',                  'description' => 'Stiff-bristle stick broom (walis ting-ting)', 'category_id' => $cat('CLEANING MATERIALS', $god), 'unit_id' => $pcs,  'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 2, 'department_id' => $dept($god)],

            // ── BOTTLED WATER ─────────────────────────────────────────────

            ['name' => 'Bottled Water', 'description' => 'Purified bottled drinking water', 'category_id' => $cat('BOTTLED WATER', $god), 'unit_id' => $btl, 'item_type' => 'consumable', 'brand' => null, 'model' => null, 'specifications' => null, 'min_stock_level' => 20, 'department_id' => $dept($god)],

        ];

        foreach ($items as $itemData) {
            if ($itemData['category_id'] && $itemData['department_id']) {
                Item::firstOrCreate(
                    ['name' => $itemData['name'], 'department_id' => $itemData['department_id']],
                    $itemData
                );
            }
        }
    }
}
